# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://odw2017.ca"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Open Data Winnipeg 2017"
title: "Open Data Winnipeg 2017"
description: "Open Data Hackathon using City of Winnipeg Datasets."
keywords: "data, hackathon, winnipeg, cow, city, open, open-data, hack, dataset"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/code3.png"
#background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
#dynamic-typing: True
shuffle: False
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "December 2nd 2017"
  - text: "5th floor of 321 McDermot"
#  - text: "Get your tickets now!"
#  - text: "Check out <a href='http://data.winnipeg.ca/'>data.winnipeg.ca</a> to get started."
#  - text: "Want to get involved? <a href='mailto:hey@odw2017.ca?Subject=I Want To Get Involved'>Click Here</a>"
#  - text: "What will you create?"
#  - text: "What datasets are available? Come find out!" 
#  - text: "Come work other awesome developers for a few hours!"

me-img: "/img/padlock_icon_2.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False
post-preview-words: 96
paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "odw2017"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "12:30"
    description: "Doors open. Mingle and meet interesting people"

  - image: "/img/timeline/spidertocat.png"
    date: "1:00 PM"
    description: "Registration; Opening Remarks"

  - image: "/img/timeline/spidertocat.png"
    date: "1:15 PM"
    description: "Brainstorming, pitching, and distillation of ideas."

  - image: "/img/timeline/spidertocat.png"
    date: "2PM"
    description: "Start Hacking."

  - image: "/img/timeline/baracktocat.jpg"
    date: "6PM"
    description: "Awesome Awesome Dinner. Catered by PEG Beer Co."

  - image: "/img/timeline/baracktocat.jpg"
    date: "8PM"
    description: "Show and Tell. Awards. Celebrate!"


# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "your@email.here"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

#social:
#  - title: "facebook"
#    url: "https://facebook.com/"
#  - title: "twitter"
#    url: "https://twitter.com/"
#  - title: "github"
#    url: "https://github.com/PanosSakkos/personal-jekyll-theme"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

#keybase-username: johnsmith
#keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
# Faq: 'faq'
#  Blog: 'latest-post'
  Timeline: 'timeline'
  Partners: 'partners'
  Map: 'map'
#  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
